service: se-tg-bot

frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-1  # Singapore
  runtime: python3.10 # AWS Lambda supports up to Python 3.10
  architecture: arm64

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - 'src/**'
    - '!node_modules/**'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - '!venv/**'
    - '!assets/**'
    - '!scripts/**'
    - '!terraform/**'

functions:
  tg_bot: ${file(./src/tg_bot/serverless.yml):TG-BOT}
