service: se-tg-bot

frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-1  # Singapore
  runtime: python3.10 # AWS Lambda supports up to Python 3.10

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  tg-bot:
    handler: src/tg-bot.handler
    timeout: 15 # seconds
    memorySize: 128 # mb
    events:
      - http:
          path: /tg-bot
          method: post
          metrics: true
    package:
      patterns:
        - '!node_modules/**'
        - '!package.json'
        - '!package-lock.json'
        - '!README.md'
        - '!venv/**'
    environment:
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}