service: se-tg-bot

frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-1  # Singapore
  runtime: python3.10 # AWS Lambda supports up to Python 3.10

plugins:
  - serverless-python-requirements

functions:
  tg-bot:
    handler: src/tg-bot.handler
    timeout: 15 # seconds
    memorySize: 1024 # mb
    events:
      - http:
          path: /tg-bot
          method: post
          metrics: true
    environment:
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

    package:
      patterns:
        - src/tg-bot.py
        - '!node_modules/**'
        - '!package.json'
        - '!package-lock.json'
        - 'requirements.txt'
        - 'serverless.yml'
        - '!README.md'
        - '!.serverless/**'
        - '!venv/**'
        - '!.gitignore'