service: se-tg-bot
frameworkVersion: '3'

custom:
  config: ${file(./.config/config.yml):CONFIG}

provider:
  name: aws
  region: ap-southeast-1  # Singapore
  runtime: ${self:custom.config.provider.runtime}
  architecture: ${self:custom.config.provider.architecture}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

package:
  individually: true
  patterns:
    - 'src/**'
    - '!node_modules/**'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - '!venv/**'
    - '!assets/**'
    - '!scripts/**'
    - '!terraform/**'

functions:
  tg_bot: ${file(./src/tg_bot/serverless.yml):TG-BOT}
  registration: ${file(./src/registration/serverless.yml):REGISTRATION}
