org: soulextreme
app: se-tg-bot

service: se-tg-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: ap-southeast-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  hello:
    name: test-lambda
    handler: src/handler.hello
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"