# REQUIRED FOR LINK WITH SERVERLESS DASHBOARD
org: soulextreme
app: se-tg-bot


service         : se-tg-bot
frameworkVersion: '3'

# Cloud Provider
provider:
  name    : aws
  runtime : python3.10              # AWS Lambda supports up to Python 3.10
  region  : ap-southeast-1          # Singapore

  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

functions:
  tg-bot:
    handler   : src/tg-bot.handler
    timeout   : 5                   # seconds
    memorySize: 128                 # mb
    requirements:
      file: src/requirements.txt

plugins:
  - serverless-plugin-canary-deployments
  - serverless-python-requirements