service: se-tg-bot

frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-1  # Singapore
  runtime: python3.10 # AWS Lambda supports up to Python 3.10
  architecture: arm64

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  tg-bot: ${file(./src/tg-bot/serverless.yml):TG-BOT}