# REQUIRED FOR LINK WITH SERVERLESS DASHBOARD
org: soulextreme
app: se-tg-bot


service         : se-tg-bot
frameworkVersion: '3'

# Cloud Provider
provider:
  name    : aws
  runtime : python3.10
  region  : ap-southeast-1          # Singapore

functions:
  tg-bot:
    handler   : src/tg-bot.handler
    timeout   : 5                   # seconds
    memorySize: 128                 # mb
