TG-BOT:
  handler: src/tg_bot/tg_bot.handler
  timeout: 15 # seconds
  memorySize: 128 # mb
  events:
    - http:
        path: src/tg_bot
        method: post
  package:
    patterns:
      - 'src/**'
      - '!node_modules/**'
      - '!package.json'
      - '!package-lock.json'
      - '!README.md'
      - '!venv/**'
      - '!assets'
      - '!scripts'
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}