TG-BOT:
  handler: src/tg_bot/tg_bot.handler
  timeout: ${self:custom.config.lambda.timeout}
  memorySize: ${self:custom.config.lambda.memorySize}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/personal-particulars"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/member-profile"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/chat-state"
  events:
    - http:
        path: src/tg_bot
        method: post
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    STRIPE_TOKEN: ${env:STRIPE_TOKEN}
