REGISTRATION:
  handler: src/registration/registration.handler
  timeout: 15 # seconds
  memorySize: 256 # mb
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/personal-particulars"
  events:
    - http:
        path: src/registration
        method: post
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
