name: Deploy SE Telegram Bot

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tg-bot-deploy.yml'
      - 'scripts/**'
      - 'src/**'
      - 'requirements.txt'
      - 'serverless.yml'
  workflow_dispatch:
    branches:
      - main
    paths:
      - '.github/workflows/tg-bot-deploy.yml'
      - 'scripts/**'
      - 'src/**'
      - 'requirements.txt'
      - 'serverless.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Serverless Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          STRIPE_TOKEN: ${{ secrets.STRIPE_TOKEN }}
          STAGE: dev
        run: |
          echo "Installing Serverless & Plugins"
          pnpm install serverless -g
          pnpm install serverless-python-requirements serverless-iam-roles-per-function
          echo "Deploying..."
          sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --verbose
          sls deploy --verbose

  checkScriptChanges:
    needs: deploy
    runs-on: ubuntu-latest
    outputs:
      set_webhook_changed: ${{ steps.changes.outputs.set_webhook }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            set_webhook:
              - 'scripts/set_webhook'

  scripts:
    needs: checkScriptChanges
    runs-on: ubuntu-latest
    if: ${{ needs.checkScriptChanges.outputs.set_webhook_changed == 'true' }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Python Requirements
        run: pip install requests

      - name: Set Webhook
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_BOT_APIGW_ENDPOINT: ${{ secrets.TG_BOT_APIGW_ENDPOINT }}
        run: |
          echo "Setting se-tg-bot webhook"
          python scripts/set_webhook.py